/*
 * Universidad Politecnica de San Luis Potosi
 * Programacion III Java
 * Programacion Orientada a Objetos
 */
package Mesero;

import cc_coffe.ExcepcionesPropias;
import java.sql.*;
import javax.swing.JOptionPane;
import cc_coffe.Entidad;
import cc_coffe.Login;
import cc_coffe.MenuMesero;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 * Esta clase esta diseñada para dar de alta un pedido, por lo que esta es la que usa el mesero
 * @author Ana Karen Cuenca Esquivel
 */
public class Pedidos extends javax.swing.JFrame {
    /**
     * banderas para seguir con la alta del pedido
     */
    boolean bandera=true,bandera2=true,bandera3;
    /**
     * ayuda a la posicion del mouse y asi poder usar el panel como barra de navegacion
     */
    int xMouse,yMouse;
    /**
     * Nos ayuda con la conexion a la base de datos
     */
    private final Connection con;
    /**
     * Este objeto nos ayuda con las consultas realizadas
     */
    private final Entidad pedido;
    /**
     * Guarda las imagenes de bebidas
     */
    ImageIcon ImagenB[]=new ImageIcon[11];
    /**
     * Guarda las imagenes de platillos
     */
    ImageIcon ImagenP[]=new ImageIcon[5];
    /**
     * Contadores para platillos y bebidas, nos ayudan a la posicion de cada producto
     */
    int cont1=1,cont2=1;
    
    /**
     * En el constructor, definimos el icono que se va a mostrar al ejecutar el programa,
     * usa @param con para unir con el objeto que creamos de conexion, inicializamos la instancia
     * con {@link Entidad#Entidad(java.sql.Connection) , inicializamos componentes, colocamos el titulo,
     * posicion, que no sea reajustable. Cargamos las imagenes con un ciclo for, se muestra la primera imagen y 
     * usamos {@link #consultarBebida(int)} para mostrar la informacion.
     */
    public Pedidos(Connection con) {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/coffee.png"));
        this.setIconImage(icon);
        this.con = con;
        pedido = new Entidad(this.con);
        initComponents();
        this.setTitle("Alta pedido");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        for (int i = 1; i <= 10; i++) {
            ImagenB[i]=new ImageIcon(getClass().getResource("/img/img"+i+".jpg"));
        }
        
        lblBebida.setIcon(ImagenB[1]);
        try {
            consultarBebida(cont2);
        } catch (SQLException e) {
            System.out.println("ERROR: "+e);
        }
        for (int i = 1; i <= 4; i++) {
            ImagenP[i]=new ImageIcon(getClass().getResource("/img/imgg"+i+".jpg"));
        }
        lblPlatillo.setIcon(ImagenP[1]);
        try {
            consultarPlatillo(cont2);
        } catch (SQLException e) {
            System.out.println("ERROR: "+e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCantP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfCantB = new javax.swing.JTextField();
        btnEliP = new javax.swing.JButton();
        btnPedir = new javax.swing.JButton();
        btnEliB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btn1Prev = new javax.swing.JButton();
        lblPlatillo = new javax.swing.JLabel();
        btn2Next = new javax.swing.JButton();
        btn2Prev = new javax.swing.JButton();
        lblBebida = new javax.swing.JLabel();
        tfNombreB = new javax.swing.JTextField();
        tfNombreP = new javax.swing.JTextField();
        btn1Next = new javax.swing.JButton();
        tfPrecioB = new javax.swing.JLabel();
        tfPrecioP = new javax.swing.JLabel();
        boxMesas = new javax.swing.JComboBox<>();
        precioB = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        desB = new javax.swing.JTextArea();
        precioP = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        descP = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta de Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 153, 0))); // NOI18N

        jLabel1.setText("Mesa:");

        jLabel2.setText("Nombre cliente:");

        tfNombre.setBorder(null);

        jLabel3.setText("Platillo:");

        jLabel4.setText("Bebidas");

        jLabel5.setText("Cantidad:");

        tfCantP.setBorder(null);

        jLabel6.setText("Cantidad:");

        tfCantB.setBorder(null);

        btnEliP.setBackground(new java.awt.Color(255, 0, 0));
        btnEliP.setForeground(new java.awt.Color(255, 255, 255));
        btnEliP.setText("Eliminar platillo");
        btnEliP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliPActionPerformed(evt);
            }
        });

        btnPedir.setBackground(new java.awt.Color(255, 153, 51));
        btnPedir.setForeground(new java.awt.Color(126, 76, 0));
        btnPedir.setText("Añadir pedido");
        btnPedir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        btnEliB.setBackground(new java.awt.Color(255, 0, 0));
        btnEliB.setForeground(new java.awt.Color(255, 255, 255));
        btnEliB.setText("Eliminar bebida");
        btnEliB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliBActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha");

        tfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFechaActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 153, 51));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(126, 76, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btn1Prev.setBackground(new java.awt.Color(126, 76, 0));
        btn1Prev.setText("<");
        btn1Prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1PrevActionPerformed(evt);
            }
        });

        lblPlatillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlatillo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(126, 76, 0), 3, true));

        btn2Next.setBackground(new java.awt.Color(126, 76, 0));
        btn2Next.setText(">");
        btn2Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2NextActionPerformed(evt);
            }
        });

        btn2Prev.setBackground(new java.awt.Color(126, 76, 0));
        btn2Prev.setText("<");
        btn2Prev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn2Prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2PrevActionPerformed(evt);
            }
        });

        lblBebida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBebida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(126, 76, 0), 3, true));

        tfNombreB.setEditable(false);
        tfNombreB.setBorder(null);
        tfNombreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreBActionPerformed(evt);
            }
        });

        tfNombreP.setEditable(false);
        tfNombreP.setBorder(null);
        tfNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombrePActionPerformed(evt);
            }
        });

        btn1Next.setBackground(new java.awt.Color(126, 76, 0));
        btn1Next.setText(">");
        btn1Next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1NextActionPerformed(evt);
            }
        });

        boxMesas.setBackground(new java.awt.Color(255, 255, 255));
        boxMesas.setForeground(new java.awt.Color(126, 76, 0));
        boxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        boxMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMesasActionPerformed(evt);
            }
        });

        precioB.setEditable(false);
        precioB.setBorder(null);

        desB.setColumns(20);
        desB.setRows(5);
        jScrollPane3.setViewportView(desB);

        precioP.setEditable(false);
        precioP.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(126, 76, 0));

        jSeparator3.setBackground(new java.awt.Color(126, 76, 0));

        descP.setColumns(20);
        descP.setRows(5);
        jScrollPane2.setViewportView(descP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(boxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(107, 107, 107)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(precioB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfCantP)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnEliP)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(tfPrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btn1Next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn2Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliB)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator3)
                                            .addComponent(tfCantB, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(lblBebida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btn2Next, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addComponent(tfPrecioB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPedir)
                                .addGap(313, 313, 313)
                                .addComponent(btnRegresar)
                                .addGap(67, 67, 67)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(tfPrecioB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tfNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(tfPrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn2Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn1Next, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btn2Next, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btn1Prev, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCantP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(tfCantB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEliP)
                                    .addComponent(btnEliB))
                                .addGap(18, 18, 18)
                                .addComponent(btnPedir)
                                .addContainerGap(18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegresar)
                                .addGap(19, 19, 19))))))
        );

        jPanel2.setBackground(new java.awt.Color(126, 76, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coffee.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(443, 443, 443))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Borra el contenido que haya en cantidad de platillo
     * @param evt 
     */
    private void btnEliPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliPActionPerformed
        //tfPlatillo.setText("");
        tfCantP.setText("");
    }//GEN-LAST:event_btnEliPActionPerformed

   private void consultarBebida(int idB) throws SQLException{
        String query="SELECT * FROM bebidas WHERE id_bebida='"+idB+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        
        ResultSet rs=stmt.executeQuery();
        if(rs.next()){
            tfNombreB.setText(rs.getString("nombre_bebida"));
            precioB.setText(rs.getString("precio_bebida"));
            desB.setText(rs.getString("descripcion_bebida"));
        }  else{
            JOptionPane.showMessageDialog(null, "No se encontro info bebida");
        }   
    }
   private void consultarPlatillo(int idP) throws SQLException{
        String query="SELECT * FROM platillos WHERE id_platillo='"+idP+"'";
        PreparedStatement stmt = con.prepareStatement(query);
        
        ResultSet rs=stmt.executeQuery();
        if(rs.next()){
            tfNombreP.setText(rs.getString("nombre_platillo"));
            precioP.setText(rs.getString("precio_platillo"));
            descP.setText(rs.getString("descripcion_platillo"));
        }  else{
            JOptionPane.showMessageDialog(null, "No se encontro info platillo");
        }   
    }
   private void mostrarInfo() throws SQLException{
       consultarPlatillo(cont1);
       consultarBebida(cont2);
   }
    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        ExcepcionesPropias exc = new ExcepcionesPropias();
        try {
            mostrarInfo();
        } catch (SQLException ex) {
            Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        //verificar que ha llenado todos los espacios
        try{
            if(tfNombre.getText().equals(" ") || tfFecha.getText().equals(" ") || !bandera){
                JOptionPane.showMessageDialog(this, "Faltan datos por llenar o no hay mesa disponible");
            }else{
                try {
                    bandera2=pedido.checarIngredientesP(cont1);
                    bandera3=pedido.checarIngredientesB(cont2);

                    if(!bandera2 && bandera3){
                        JOptionPane.showMessageDialog(this, "No se puede realizar el platillo");
                        tfCantP.setText("");
                    }else if(bandera&&!bandera3){
                        JOptionPane.showMessageDialog(this, "No se puede realizar la bebida");
                        tfCantB.setText("");
                    }else{//si hay suficiente ingredientes
                        exc.cantidad(Integer.parseInt(tfCantP.getText()));
                        exc.cantidad(Integer.parseInt(tfCantB.getText()));
                        String selectedValue = (String) boxMesas.getSelectedItem();
                        int mesaSeleccionada = Integer.parseInt(selectedValue);
                        pedido.altaPedido(mesaSeleccionada, tfNombre.getText(),Integer.parseInt(tfCantP.getText()), 
                                Integer.parseInt(tfCantB.getText()),cont1, cont2, tfFecha.getText(), "En progreso");
                        if(bandera2 && bandera3){
                            pedido.reducirIngredienteB(cont2);
                            pedido.reducirIngredienteP(cont1);
                        }
                        JOptionPane.showMessageDialog(this, "Registro guardado");
                        tfNombre.setText("");
                        tfFecha.setText("");
                        tfCantP.setText("");
                        tfCantB.setText("");
                    }

                } catch (SQLException ex) {
                    System.out.println("ERROR try-catch pedido: "+ex);
                }

            }
        }catch(Exception er){
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad correcta: "+er);
            tfCantP.setText("");
            tfCantB.setText("");
        }
        
    }//GEN-LAST:event_btnPedirActionPerformed

    private void btnEliBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliBActionPerformed
        //tfBebida.setText("");
        tfCantB.setText("");
    }//GEN-LAST:event_btnEliBActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new MenuMesero(con).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFechaActionPerformed

    private void btn1PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1PrevActionPerformed
        if(cont1==1){
            cont1=5;
        }
        cont1--;
        lblPlatillo.setIcon(ImagenP[cont1]);
        
        try{
            String query="SELECT * FROM platillos WHERE id_platillo='"+cont1+"'";
            PreparedStatement stmt = con.prepareStatement(query);

            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                tfNombreP.setText(rs.getString("nombre_platillo"));
                precioP.setText(rs.getString("precio_platillo"));
                descP.setText(rs.getString("descripcion_platillo"));
            }  else{
                JOptionPane.showMessageDialog(null, "No se encontro info platillo");
            }   
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btn1PrevActionPerformed

    private void btn2NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2NextActionPerformed
        if (cont2 == 10) {
            cont2 = 0;
        }
        cont2++;
        lblBebida.setIcon(ImagenB[cont2]);
        
        try{
            String query="SELECT * FROM bebidas WHERE id_bebida='"+cont2+"'";
            PreparedStatement stmt = con.prepareStatement(query);

            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                tfNombreB.setText(rs.getString("nombre_bebida"));
                precioB.setText(rs.getString("precio_bebida"));
                desB.setText(rs.getString("descripcion_bebida"));
            }  else{
                JOptionPane.showMessageDialog(null, "No se encontro info bebida");
            } 
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btn2NextActionPerformed

    private void btn2PrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2PrevActionPerformed
        if(cont2==1){
            cont2=11;
        }
        cont2--;
        lblBebida.setIcon(ImagenB[cont2]);
        
        
        try{
            String query="SELECT * FROM bebidas WHERE id_bebida='"+cont2+"'";
            PreparedStatement stmt = con.prepareStatement(query);

            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                tfNombreB.setText(rs.getString("nombre_bebida"));
                precioB.setText(rs.getString("precio_bebida"));
                desB.setText(rs.getString("descripcion_bebida"));
            }  else{
                JOptionPane.showMessageDialog(null, "No se encontro info bebida");
            } 
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btn2PrevActionPerformed

    private void tfNombreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreBActionPerformed

    private void tfNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombrePActionPerformed

    private void btn1NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1NextActionPerformed
        if (cont1 == 4) {
            cont1 = 0;
        }
        cont1++;
        lblPlatillo.setIcon(ImagenP[cont1]);
        
        try{
            String query="SELECT * FROM platillos WHERE id_platillo='"+cont1+"'";
            PreparedStatement stmt = con.prepareStatement(query);

            ResultSet rs=stmt.executeQuery();
            if(rs.next()){
                tfNombreP.setText(rs.getString("nombre_platillo"));
                precioP.setText(rs.getString("precio_platillo"));
                descP.setText(rs.getString("descripcion_platillo"));
                
            }  else{
                JOptionPane.showMessageDialog(null, "No se encontro info platillo");
            }   
        }catch(SQLException e){
            System.out.println("Error: "+e);
        }
    }//GEN-LAST:event_btn1NextActionPerformed

    private void boxMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMesasActionPerformed
        bandera=pedido.dispoMesa(Integer.parseInt(boxMesas.getSelectedItem().toString()));
        if(bandera==false){
            JOptionPane.showMessageDialog(null, "ERROR: Mesa no disponible");
        }else{
            System.out.println("Mesa disponible:)");
        }
    }//GEN-LAST:event_boxMesasActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);

    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMesas;
    private javax.swing.JButton btn1Next;
    private javax.swing.JButton btn1Prev;
    private javax.swing.JButton btn2Next;
    private javax.swing.JButton btn2Prev;
    private javax.swing.JButton btnEliB;
    private javax.swing.JButton btnEliP;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextArea desB;
    private javax.swing.JTextArea descP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JLabel lblBebida;
    public static javax.swing.JLabel lblPlatillo;
    private javax.swing.JTextField precioB;
    private javax.swing.JTextField precioP;
    private javax.swing.JTextField tfCantB;
    private javax.swing.JTextField tfCantP;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombreB;
    private javax.swing.JTextField tfNombreP;
    private javax.swing.JLabel tfPrecioB;
    private javax.swing.JLabel tfPrecioP;
    // End of variables declaration//GEN-END:variables
}
